# Generated by Django 2.1.4 on 2018-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='课程名')),
                ('classCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='课程代码')),
                ('classTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='课程时间')),
                ('teacher', models.CharField(blank=True, max_length=20, null=True, verbose_name='老师')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='地点')),
            ],
        ),
    ]
