# Generated by Django 2.1.4 on 2018-12-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(blank=True, max_length=100, null=True, verbose_name='课程名')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='老师')),
                ('studentNum', models.CharField(blank=True, max_length=100, null=True, verbose_name='学号')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNum', models.CharField(blank=True, max_length=100, null=True, verbose_name='学号')),
                ('classCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='课程代码')),
                ('Grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='成绩')),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='className',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='class',
            name='classCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程代码'),
        ),
        migrations.AlterField(
            model_name='class',
            name='classTime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程时间'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='老师'),
        ),
    ]
