# Generated by Django 2.1.4 on 2018-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181205_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(blank=True, max_length=100, null=True, verbose_name='学生名字')),
                ('studentNum', models.CharField(blank=True, max_length=100, null=True, verbose_name='学号')),
            ],
        ),
    ]
