# Generated by Django 2.1.4 on 2018-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(blank=True, max_length=100, null=True, verbose_name='老师名字')),
                ('teacherNum', models.CharField(blank=True, max_length=100, null=True, verbose_name='工号')),
            ],
        ),
    ]
