# Generated by Django 2.1.4 on 2018-12-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(blank=True, max_length=20, verbose_name='身份'),
        ),
    ]
